/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS "company_fs" (
	"종목코드" VARCHAR(50) NOT NULL,
	"기준년도" VARCHAR(50) NOT NULL,
	"자산총계" DOUBLE PRECISION NULL DEFAULT NULL,
	"유동자산" DOUBLE PRECISION NULL DEFAULT NULL,
	"비유동자산" DOUBLE PRECISION NULL DEFAULT NULL,
	"부채총계" DOUBLE PRECISION NULL DEFAULT NULL,
	"유동부채" DOUBLE PRECISION NULL DEFAULT NULL,
	"이자발생부채" DOUBLE PRECISION NULL DEFAULT NULL,
	"순부채" DOUBLE PRECISION NULL DEFAULT NULL,
	"비유동부채" DOUBLE PRECISION NULL DEFAULT NULL,
	"자본총계" DOUBLE PRECISION NULL DEFAULT NULL,
	"자본총계_지배" DOUBLE PRECISION NULL DEFAULT NULL,
	"자본금" BIGINT NULL DEFAULT NULL,
	"자본잉여금" DOUBLE PRECISION NULL DEFAULT NULL,
	"이익잉여금" DOUBLE PRECISION NULL DEFAULT NULL,
	"비지배주주지분" DOUBLE PRECISION NULL DEFAULT NULL,
	"매출액" DOUBLE PRECISION NULL DEFAULT NULL,
	"매출원가" DOUBLE PRECISION NULL DEFAULT NULL,
	"매출총이익" DOUBLE PRECISION NULL DEFAULT NULL,
	"판매비와관리비" DOUBLE PRECISION NULL DEFAULT NULL,
	"영업이익" DOUBLE PRECISION NULL DEFAULT NULL,
	"금융수익" DOUBLE PRECISION NULL DEFAULT NULL,
	"금융비용" DOUBLE PRECISION NULL DEFAULT NULL,
	"기타영업외수익" DOUBLE PRECISION NULL DEFAULT NULL,
	"기타영업외비용" DOUBLE PRECISION NULL DEFAULT NULL,
	"감가상각비_판관비" BIGINT NULL DEFAULT NULL,
	"세전계속사업이익" DOUBLE PRECISION NULL DEFAULT NULL,
	"당기순이익" DOUBLE PRECISION NULL DEFAULT NULL,
	"당기순이익_지배" DOUBLE PRECISION NULL DEFAULT NULL,
	"당기순이익_비지배" DOUBLE PRECISION NULL DEFAULT NULL,
	"영업활동으로인한현금흐름" DOUBLE PRECISION NULL DEFAULT NULL,
	"감가상각비_현금흐름표" DOUBLE PRECISION NULL DEFAULT NULL,
	"운전자본증감" DOUBLE PRECISION NULL DEFAULT NULL,
	"투자활동으로인한현금흐름" DOUBLE PRECISION NULL DEFAULT NULL,
	"CAPEX" DOUBLE PRECISION NULL DEFAULT NULL,
	"재무활동으로인한현금흐름" DOUBLE PRECISION NULL DEFAULT NULL,
	"영업투자재무활동기타현금흐름" TEXT NULL DEFAULT NULL,
	"현금의증가" DOUBLE PRECISION NULL DEFAULT NULL,
	"FreeCashFlow2" DOUBLE PRECISION NULL DEFAULT NULL,
	"EBITDA2" DOUBLE PRECISION NULL DEFAULT NULL,
	"EBIT" DOUBLE PRECISION NULL DEFAULT NULL,
	"IC" DOUBLE PRECISION NULL DEFAULT NULL,
	"NOPLAT" DOUBLE PRECISION NULL DEFAULT NULL,
	"EV" DOUBLE PRECISION NULL DEFAULT NULL,
	"EV2" DOUBLE PRECISION NULL DEFAULT NULL,
	"매출총이익률" DOUBLE PRECISION NULL DEFAULT NULL,
	"영업이익률" DOUBLE PRECISION NULL DEFAULT NULL,
	"순이익률" DOUBLE PRECISION NULL DEFAULT NULL,
	"EBITDA2마진율" DOUBLE PRECISION NULL DEFAULT NULL,
	"ROE_지배" DOUBLE PRECISION NULL DEFAULT NULL,
	"ROA" DOUBLE PRECISION NULL DEFAULT NULL,
	"ROIC" DOUBLE PRECISION NULL DEFAULT NULL,
	"매출액증가율_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"매출액증가율_QoQ" TEXT NULL DEFAULT NULL,
	"영업이익증가율_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"영업이익증가율_QoQ" TEXT NULL DEFAULT NULL,
	"순이익증가율_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"순이익증가율_QoQ" TEXT NULL DEFAULT NULL,
	"순이익증가율_지배_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"순이익증가율_지배_QoQ" TEXT NULL DEFAULT NULL,
	"EBITDA2증가율_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"EBITDA2증가율_QoQ" TEXT NULL DEFAULT NULL,
	"EBIT증가율_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"EBIT증가율_QoQ" TEXT NULL DEFAULT NULL,
	"부채비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"유동비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"자기자본비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"이자보상배율" DOUBLE PRECISION NULL DEFAULT NULL,
	"비유동비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"차입금비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"순부채비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"자본유보율" DOUBLE PRECISION NULL DEFAULT NULL,
	"총자산회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"매출채권회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"재고자산회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"매입채무회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"타인자본회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"자기자본회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"자본금회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"EPS_지배" DOUBLE PRECISION NULL DEFAULT NULL,
	"BPS_지배" DOUBLE PRECISION NULL DEFAULT NULL,
	"CPS" DOUBLE PRECISION NULL DEFAULT NULL,
	"CEPS" DOUBLE PRECISION NULL DEFAULT NULL,
	"SPS" DOUBLE PRECISION NULL DEFAULT NULL,
	"EBITDA2PS" DOUBLE PRECISION NULL DEFAULT NULL,
	"EBITPS" DOUBLE PRECISION NULL DEFAULT NULL,
	"NetDebt/Share" DOUBLE PRECISION NULL DEFAULT NULL,
	"EPS증가율_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"EPS증가율_QoQ" TEXT NULL DEFAULT NULL,
	"BPS증가율_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"BPS증가율_QoQ" TEXT NULL DEFAULT NULL,
	"수정DPS_보통주_기말현금" TEXT NULL DEFAULT NULL,
	"수정DPS_보통주_연간현금" BIGINT NULL DEFAULT NULL,
	"수정DPS_우선주_기말현금" TEXT NULL DEFAULT NULL,
	"수정DPS_우선주_연간현금" DOUBLE PRECISION NULL DEFAULT NULL,
	"현금배당성향" DOUBLE PRECISION NULL DEFAULT NULL,
	"현금배당률_보통주_기말_액면가" TEXT NULL DEFAULT NULL,
	"현금배당률_보통주_연간_액면가" BIGINT NULL DEFAULT NULL,
	"현금배당수익률_보통주_연간_수정주가" DOUBLE PRECISION NULL DEFAULT NULL,
	"현금배당수익률_우선주_연간_수정주가" TEXT NULL DEFAULT NULL,
	"시가배당률_보통주_기말_KRX기준" TEXT NULL DEFAULT NULL,
	"P/E" DOUBLE PRECISION NULL DEFAULT NULL,
	"P/B" DOUBLE PRECISION NULL DEFAULT NULL,
	"P/C" DOUBLE PRECISION NULL DEFAULT NULL,
	"P/CE" DOUBLE PRECISION NULL DEFAULT NULL,
	"P/S" DOUBLE PRECISION NULL DEFAULT NULL,
	"P/FCF2" DOUBLE PRECISION NULL DEFAULT NULL,
	"PEG_YoY" DOUBLE PRECISION NULL DEFAULT NULL,
	"EV/EBITDA2" DOUBLE PRECISION NULL DEFAULT NULL,
	"EV/EBIT" DOUBLE PRECISION NULL DEFAULT NULL,
	"EV/Sales" DOUBLE PRECISION NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드", "기준년도")
);

CREATE TABLE IF NOT EXISTS "kospi_200" (
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드")
);

CREATE TABLE IF NOT EXISTS "news" (
	"stock_code" VARCHAR(50) NOT NULL,
	"title" TEXT NULL DEFAULT NULL,
	"link" TEXT NOT NULL,
	"reg_date" TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("stock_code", "link")
);

CREATE TABLE IF NOT EXISTS "opt10001" (
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	"결산월" INTEGER NULL DEFAULT NULL,
	"액면가" DOUBLE PRECISION NULL DEFAULT NULL,
	"자본금" INTEGER NULL DEFAULT NULL,
	"상장주식" INTEGER NULL DEFAULT NULL,
	"신용비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"연중최고" INTEGER NULL DEFAULT NULL,
	"연중최저" INTEGER NULL DEFAULT NULL,
	"시가총액" INTEGER NULL DEFAULT NULL,
	"시가총액비중" DOUBLE PRECISION NULL DEFAULT NULL,
	"외인소진률" DOUBLE PRECISION NULL DEFAULT NULL,
	"대용가" INTEGER NULL DEFAULT NULL,
	"PER" DOUBLE PRECISION NULL DEFAULT NULL,
	"EPS" INTEGER NULL DEFAULT NULL,
	"ROE" DOUBLE PRECISION NULL DEFAULT NULL,
	"PBR" DOUBLE PRECISION NULL DEFAULT NULL,
	"EV" DOUBLE PRECISION NULL DEFAULT NULL,
	"BPS" INTEGER NULL DEFAULT NULL,
	"매출액" INTEGER NULL DEFAULT NULL,
	"영업이익" INTEGER NULL DEFAULT NULL,
	"당기순이익" INTEGER NULL DEFAULT NULL,
	"250최고" INTEGER NULL DEFAULT NULL,
	"250최저" INTEGER NULL DEFAULT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	"상한가" INTEGER NULL DEFAULT NULL,
	"하한가" INTEGER NULL DEFAULT NULL,
	"기준가" INTEGER NULL DEFAULT NULL,
	"예상체결가" INTEGER NULL DEFAULT NULL,
	"예상체결수량" INTEGER NULL DEFAULT NULL,
	"250최고가일" DATE NULL DEFAULT NULL,
	"250최고가대비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"250최저가일" DATE NULL DEFAULT NULL,
	"250최저가대비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"대비기호" INTEGER NULL DEFAULT NULL,
	"전일대비" INTEGER NULL DEFAULT NULL,
	"등락율" DOUBLE PRECISION NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"거래대비" DOUBLE PRECISION NULL DEFAULT NULL,
	"액면가단위" TEXT NULL DEFAULT NULL,
	"유통주식" INTEGER NULL DEFAULT NULL,
	"유통비율" DOUBLE PRECISION NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드")
);

CREATE TABLE IF NOT EXISTS "opt10027" (
	"종목분류" VARCHAR(50) NULL DEFAULT 'NULL::character varying',
	"시장구분" VARCHAR(50) NOT NULL,
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"전일대비기호" INTEGER NULL DEFAULT NULL,
	"전일대비" INTEGER NULL DEFAULT NULL,
	"등락률" DOUBLE PRECISION NULL DEFAULT NULL,
	"매도잔량" BIGINT NULL DEFAULT NULL,
	"매수잔량" BIGINT NULL DEFAULT NULL,
	"현재거래량" BIGINT NULL DEFAULT NULL,
	"체결강도" DOUBLE PRECISION NULL DEFAULT NULL,
	"횟수" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드")
);

CREATE TABLE IF NOT EXISTS "opt10030" (
	"시장구분" VARCHAR(50) NOT NULL,
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"전일대비기호" INTEGER NULL DEFAULT NULL,
	"전일대비" INTEGER NULL DEFAULT NULL,
	"등락률" DOUBLE PRECISION NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"전일비" DOUBLE PRECISION NULL DEFAULT NULL,
	"거래회전율" DOUBLE PRECISION NULL DEFAULT NULL,
	"거래금액" BIGINT NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드")
);

CREATE TABLE IF NOT EXISTS "opt10033" (
	"시장구분" VARCHAR(50) NOT NULL,
	"종목정보" VARCHAR(50) NULL DEFAULT 'NULL::character varying',
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"전일대비기호" INTEGER NULL DEFAULT NULL,
	"전일대비" INTEGER NULL DEFAULT NULL,
	"등락률" DOUBLE PRECISION NULL DEFAULT NULL,
	"신용비율" DOUBLE PRECISION NULL DEFAULT NULL,
	"매도잔량" BIGINT NULL DEFAULT NULL,
	"매수잔량" BIGINT NULL DEFAULT NULL,
	"현재거래량" BIGINT NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드")
);

CREATE TABLE IF NOT EXISTS "opt10081" (
	"종목코드" VARCHAR(50) NOT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"거래대금" BIGINT NULL DEFAULT NULL,
	"일자" DATE NOT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드", "일자")
);

CREATE TABLE IF NOT EXISTS "opt10082" (
	"종목코드" VARCHAR(50) NOT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"거래대금" BIGINT NULL DEFAULT NULL,
	"일자" DATE NOT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드", "일자")
);

CREATE TABLE IF NOT EXISTS "opt10083" (
	"종목코드" VARCHAR(50) NOT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"거래대금" BIGINT NULL DEFAULT NULL,
	"일자" DATE NOT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드", "일자")
);

CREATE TABLE IF NOT EXISTS "opt10086" (
	"종목코드" VARCHAR(50) NOT NULL,
	"날짜" DATE NOT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	"종가" INTEGER NULL DEFAULT NULL,
	"전일비" INTEGER NULL DEFAULT NULL,
	"등락률" DOUBLE PRECISION NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"금액" BIGINT NULL DEFAULT NULL,
	"신용비" DOUBLE PRECISION NULL DEFAULT NULL,
	"개인" INTEGER NULL DEFAULT NULL,
	"기관" INTEGER NULL DEFAULT NULL,
	"외인수량" INTEGER NULL DEFAULT NULL,
	"외국계" INTEGER NULL DEFAULT NULL,
	"프로그램" INTEGER NULL DEFAULT NULL,
	"외인비" DOUBLE PRECISION NULL DEFAULT NULL,
	"체결강도" DOUBLE PRECISION NULL DEFAULT NULL,
	"외인보유" DOUBLE PRECISION NULL DEFAULT NULL,
	"외인비중" DOUBLE PRECISION NULL DEFAULT NULL,
	"외인순매수" INTEGER NULL DEFAULT NULL,
	"기관순매수" INTEGER NULL DEFAULT NULL,
	"개인순매수" INTEGER NULL DEFAULT NULL,
	"신용잔고율" DOUBLE PRECISION NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드", "날짜")
);

CREATE TABLE IF NOT EXISTS "opt20002" (
	"업종코드" VARCHAR(50) NOT NULL,
	"업종명" TEXT NULL DEFAULT NULL,
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"전일대비기호" INTEGER NULL DEFAULT NULL,
	"전일대비" INTEGER NULL DEFAULT NULL,
	"등락률" DOUBLE PRECISION NULL DEFAULT NULL,
	"현재거래량" BIGINT NULL DEFAULT NULL,
	"매도호가" INTEGER NULL DEFAULT NULL,
	"매수호가" INTEGER NULL DEFAULT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("업종코드", "종목코드")
);

CREATE TABLE IF NOT EXISTS "opt20003" (
	"업종코드" VARCHAR(50) NOT NULL,
	"업종명" TEXT NULL DEFAULT NULL,
	"현재가" DOUBLE PRECISION NULL DEFAULT NULL,
	"대비기호" INTEGER NULL DEFAULT NULL,
	"전일대비" DOUBLE PRECISION NULL DEFAULT NULL,
	"등락률" DOUBLE PRECISION NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"비중" DOUBLE PRECISION NULL DEFAULT NULL,
	"거래대금" BIGINT NULL DEFAULT NULL,
	"상한" INTEGER NULL DEFAULT NULL,
	"상승" INTEGER NULL DEFAULT NULL,
	"보합" INTEGER NULL DEFAULT NULL,
	"하락" INTEGER NULL DEFAULT NULL,
	"하한" INTEGER NULL DEFAULT NULL,
	"상장종목수" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("업종코드")
);

CREATE TABLE IF NOT EXISTS "opt20006" (
	"업종코드" VARCHAR(50) NOT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"일자" DATE NOT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	"거래대금" BIGINT NULL DEFAULT NULL,
	PRIMARY KEY ("일자", "업종코드")
);

CREATE TABLE IF NOT EXISTS "opt20007" (
	"업종코드" VARCHAR(50) NOT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"일자" DATE NOT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	"거래대금" BIGINT NULL DEFAULT NULL,
	PRIMARY KEY ("일자", "업종코드")
);

CREATE TABLE IF NOT EXISTS "opt20008" (
	"업종코드" VARCHAR(50) NOT NULL,
	"현재가" INTEGER NULL DEFAULT NULL,
	"거래량" BIGINT NULL DEFAULT NULL,
	"일자" DATE NOT NULL,
	"시가" INTEGER NULL DEFAULT NULL,
	"고가" INTEGER NULL DEFAULT NULL,
	"저가" INTEGER NULL DEFAULT NULL,
	"거래대금" BIGINT NULL DEFAULT NULL,
	PRIMARY KEY ("일자", "업종코드")
);

CREATE TABLE IF NOT EXISTS "opt90002" (
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	"테마코드" VARCHAR(50) NOT NULL,
	PRIMARY KEY ("종목코드", "테마코드")
);

CREATE TABLE IF NOT EXISTS "sector" (
	"업종코드" VARCHAR(50) NOT NULL,
	"업종명" TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("업종코드")
);

CREATE TABLE IF NOT EXISTS "stock" (
	"종목코드" VARCHAR(50) NOT NULL,
	"종목명" TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("종목코드")
);

CREATE TABLE IF NOT EXISTS "theme" (
	"테마코드" VARCHAR(50) NOT NULL,
	"테마명" TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("테마코드")
);

CREATE TABLE portfolio (
	stock_date date NULL,
	stocks_num int4 NULL,
	magic float8 NULL,
	momentum float8 NULL,
	fscore float8 NULL,
	fscore_understocks float8 NULL,
	understocks float8 NULL,
	"date" varchar(10) NULL
);

CREATE TABLE portfolio_year (
	stocks_num int4 NULL,
	"rank" int4 NULL,
	"year" varchar(16) NULL,
	understocks varchar(16) NULL,
	magic varchar(16) NULL,
	momentum varchar(16) NULL,
	fscore varchar(16) NULL,
	fscore_understocks varchar(16) NULL
);

create view strategy_rank as
select AA.stocks_num,AA.stock,o.종목명,AA.cnt, o.시가총액 
from (
select C.stocks_num, C.stock, count(C.stock) as cnt from
(
   select
      A.stocks_num,
      A.year,
      case
         when B.idx = 1 then A.understocks
         when B.idx = 2 then A.magic
         when B.idx = 3 then A.momentum
         when B.idx = 4 then A.fscore
         when B.idx = 5 then A.fscore_understocks
      end as stock
   from
   (
      select stocks_num, year, understocks, magic, momentum, fscore, fscore_understocks
      from portfolio_year 
      where year = '2021'
   ) as A
   cross join (
      select 1 as idx
         union all select 2 as idx
         union all select 3 as idx
         union all select 4 as idx
         union all select 5 as idx
   ) as B
) as C
group by C.stocks_num, C.stock
order by C.stocks_num, C.count desc
) as AA
left join 
	opt10001 as o 
	on AA.stock = o.종목코드
where AA.cnt >1
order by stocks_num, cnt desc,시가총액 desc;

CREATE TABLE stock_prediction (
	stock_code varchar(50) NULL,
	stock_name text NULL,
	batch_date date NULL,
	predict_date date NULL,
	predict_value int4 NULL,
	trend varchar(10) NULL
);

CREATE TABLE value_analysis_results (
	기준년도 text NULL,
	종목코드 text NULL,
	종목명 text NULL,
	스코어 int4 NULL,
	시가총액 int4 NULL,
	"ROE" float8 NULL,
	"EPS증가율" float8 NULL,
	"PEG" float8 NULL,
	"PER" float8 NULL,
	"PSR" float8 NULL,
	"3년평균순이익률" float8 NULL,
	업종명 text NULL,
	업종코드 varchar NULL
);

CREATE TABLE public.value_analysis_results_graph (
	기준년도 text NULL,
	종목코드 text NULL,
	종목명 text NULL,
	시가총액 int4 NULL,
	"ROE" float8 NULL,
	"EPS증가율" float8 NULL,
	"PEG" float8 NULL,
	"PER" float8 NULL,
	"PSR" float8 NULL,
	"3년평균순이익률" float8 NULL
);


/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
